### ISSUE TITLE
Handle multisite support

### ISSUE THREAD

**Issue by ingeniumed** [Automattic/vip-governance-plugin#55]
Currently, it's not possible to customize the rules per network site as it's the same private directory for all of them. We should offer a way to customize this, and this could potentially be used then by those not using the plugin on VIP as well.

**Comment by smithjw1** [comment]
@josiahwold [asked](https://keepingtheirblogsgoing.wordpress.com/2023/10/04/new-feature-release-vip-governance-plugin/#comment-139246)

> Do you have a rough timescale of when that might occur? Is before end of Q1-24 likely?
Christianity Today is selecting a solution for their multisite and would be fine with a shared ruleset until their second site launches in March/April 2024.

We should slate this work to happen before then.

**Comment by smithjw1** [comment]
@josiahwold asked

> Do you have a rough timescale of when that might occur? Is before end of Q1-24 likely? A customer is selecting a solution for their multisite and would be fine with a shared ruleset until their second site launches in March/April 2024.

We should slate this work to happen before then.
