### ISSUE TITLE
Add filter to enable for programmatic JSON generation. 

### ISSUE THREAD

**Issue by smithjw1** [Automattic/vip-governance-plugin#62]
Currently, all rules are loaded via a file. This prevents more dynamic rule generation.

Could a filter be added so that rules loaded via the file could be augmented by programmatically generated JSON? Or file based loading skipped entirely if programmatic generation is in use?

**Comment by alecgeatches** [comment]
This has been added in https://github.com/Automattic/vip-governance-plugin/pull/85 via the [`vip_governance__governance_rules_json` filter](https://github.com/Automattic/vip-governance-plugin?tab=readme-ov-file#vip_governance__governance_rules_json).
