### ISSUE TITLE
Assets get enqueued with invalid URL on non-VIP deployments

### ISSUE THREAD

**Issue by marijnvdwerf** [Automattic/vip-governance-plugin#66]
**Describe the bug**
Frontend assets are enqueued with a path that can result in a 404 (.e.g `http://localhost:8080/var/www/html/wp-content/plugins/vip-governance/css/vip-governance.css?ver=1.0.5`)

**To Reproduce**
Install the plugin on a docker container running `wordpress:6.4-php8.2`.

**Expected behavior**
Assets get pushed as `wp-content/plugins/vip-governance/css/vip-governance.css?ver=1.0.5`

**Actual behavior**
Assets get pushed as `http://localhost:8080/var/www/html/wp-content/plugins/vip-governance/css/vip-governance.css?ver=1.0.5`

**Version of the plugin**
1.0.5

**Additional context**
Replacing some uses of `WPCOMVIP_GOVERNANCE_ROOT_PLUGIN_DIR` with `plugin_dir_url(WPCOMVIP_GOVERNANCE_ROOT_PLUGIN_FILE)` resolved the issue.

**Comment by smithjw1** [comment]
Thanks for reporting this so clearly and providing a solution that worked for you! 

We can take a look, but are certainly open to PRs if you would like to contribute directly.

**Comment by marijnvdwerf** [comment]
I’ll try to create a PR sometime this week.
