### ISSUE TITLE
Add support for wildcard block names when specifying block-specific settings rules

### ISSUE THREAD

**Issue by philipjohn** [Automattic/vip-governance-plugin#82]
In `allowedBlocks` we can use a wildcard to specify several blocks, like so:

```
"allowedBlocks": [
    "core-embed/*"
]
```

When tweaking the available settings we cannot do this, however:

```
"blockSettings": {
    "core-embed/*": {
        "color": {
            "text": false
        }
    },
}
```

Instead, we have to do something like this, which feels overly repetitive:

```
"blockSettings": {
	"core-embed/twitter": {
		"color": {
                    "text": false
		}
	},
	"core-embed/youtube": {
		"color": {
                    "text": false
		}
	},
	"core-embed/facebook": {
		"color": {
                    "text": false
		}
	},
	"core-embed/instagram": {
		"color": {
                    "text": false
		}
	},
	"core-embed/soundcloud": {
		"color": {
                    "text": false
		}
	},
	"core-embed/imgur": {
		"color": {
                    "text": false
		}
	},
	"core-embed/reddit": {
		"color": {
                    "text": false
		}
	},
	"core-embed/tiktok": {
		"color": {
                    "text": false
		}
	}
}
```

It'd be nice if we could use the wildcard within `blockSettings` as well.

**Comment by alecgeatches** [comment]
@philipjohn Appreciate the issue and example of your problem! This seems like a good addition to me, we'll look into this. Thank you!

**Comment by alecgeatches** [comment]
@philipjohn We've made a new release, with the main feature of allowing wildcard block names for block settings: https://github.com/Automattic/vip-governance-plugin/releases/tag/1.0.10.

We have some documentation available in the [**Wildcards** section of the README](https://github.com/Automattic/vip-governance-plugin?tab=readme-ov-file#wildcards). Please let us know if this doesn't address your use-case, and we can re-open this ticket. Thank you for the suggestion!
