### ISSUE TITLE
Governance style sheet being loaded on the front end

### ISSUE THREAD

**Issue by smithjw1** [Automattic/vip-governance-plugin#84]
It looks like our CSS enqueue loads a blank style sheet on the front end.

https://github.com/Automattic/vip-governance-plugin/blob/cde5bb56768bd509287ec215e32de0f75725faca/governance/init-governance.php#L88

Looks like we should use this instead:
https://developer.wordpress.org/reference/hooks/admin_enqueue_scripts/

**Comment by alecgeatches** [comment]
Fixed by https://github.com/Automattic/vip-governance-plugin/pull/85.
